# DisplayLink setup for Home Manager on non-NixOS hosts.
# Prefetches the driver blob, installs system units, and detects the evdi render device.
# See: https://wiki.nixos.org/wiki/Displaylink
set -euo pipefail

readonly DISPLAYLINK_NAME="displaylink-620.zip"
readonly DISPLAYLINK_URL="https://www.synaptics.com/sites/default/files/exe_files/2025-09/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu6.2-EXE.zip"
readonly EVDI_CONF="/etc/modules-load.d/evdi.conf"
readonly SERVICE_PATH="/etc/systemd/system/displaylink-server.service"
readonly UDEV_RULES="/etc/udev/rules.d/99-displaylink.rules"
readonly SWAY_ENV_DIR="${HOME}/.config/sway"
readonly SWAY_ENV_FILE="${SWAY_ENV_DIR}/displaylink-env"

log() {
  echo "[displaylink-setup] $*"
}

die() {
  echo "[displaylink-setup] ERROR: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

nixpkgs_path() {
  if [ -n "${NIXPKGS:-}" ]; then
    printf '%s' "$NIXPKGS"
    return 0
  fi

  if [ -n "${NIX_PATH:-}" ]; then
    local entry
    for entry in ${NIX_PATH//:/ }; do
      case "$entry" in
        nixpkgs=*) printf '%s' "${entry#nixpkgs=}"; return 0 ;;
      esac
    done
  fi

  printf '%s' "<nixpkgs>"
}

build_displaylink() {
  local nixpkgs
  nixpkgs="$(nixpkgs_path)"

  NIXPKGS_ALLOW_UNFREE=1 nix-build "$nixpkgs" -A displaylink --no-out-link 2>/dev/null
}

ensure_displaylink_blob() {
  require_command nix-build
  require_command nix-prefetch-url

  if build_displaylink >/dev/null; then
    log "DisplayLink driver already available in the Nix store"
    return 0
  fi

  log "Fetching DisplayLink driver into the Nix store..."
  nix-prefetch-url --name "$DISPLAYLINK_NAME" "$DISPLAYLINK_URL" >/dev/null

  build_displaylink >/dev/null || die "displaylink package build failed after prefetch"
  log "DisplayLink driver added to the Nix store"
}

detect_evdi_render_device() {
  local device="/dev/dri/card1"
  local link

  if [ -d /dev/dri/by-path ]; then
    for link in /dev/dri/by-path/pci-*-card; do
      [ -e "$link" ] || continue
      device="$(readlink -f "$link")"
      break
    done
  fi

  printf '%s' "$device"
}

write_sway_env() {
  local render_device
  render_device="$(detect_evdi_render_device)"

  mkdir -p "$SWAY_ENV_DIR"
  cat >"$SWAY_ENV_FILE" <<EOF
# Generated by displaylink-setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)
export WLR_EVDI_RENDER_DEVICE=${render_device}
EOF
  chmod 644 "$SWAY_ENV_FILE"
  log "WLR_EVDI_RENDER_DEVICE set to ${render_device}"
}

install_system_components() {
  local displaylink_pkg
  displaylink_pkg="$(build_displaylink)"

#   require_command sudo
#   sudo -v

  log "Installing udev rules"
  sudo install -Dm644 \
    "${displaylink_pkg}/lib/udev/rules.d/99-displaylink.rules" \
    "$UDEV_RULES"

  log "Installing displaylink-server systemd unit"
  sudo install -Dm644 /dev/stdin "$SERVICE_PATH" <<EOF
[Unit]
Description=DisplayLink Manager Service
Requires=systemd-udevd.service
After=systemd-udevd.service

[Service]
Type=simple
ExecStart=${displaylink_pkg}/bin/DisplayLinkManager
User=root
Group=root
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  log "Enabling evdi kernel module"
  printf '%s\n' evdi | sudo install -Dm644 /dev/stdin "$EVDI_CONF"

  sudo udevadm control --reload
  sudo systemctl daemon-reload
  sudo systemctl enable --now displaylink-server.service
  log "displaylink-server service enabled"
}

main() {
  ensure_displaylink_blob
  write_sway_env
  install_system_components
  log "DisplayLink setup complete"
}

main "$@"
